export const FETCH_LOADING = 'FETCH_LOADING'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

export const RESET_ERROR_STATE = 'RESET_ERROR_STATE'