export const FETCH_LOADING = 'FETCH_LOADING'

export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED'

export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS'
export const FETCH_CONTENT_FAILED = 'FETCH_CONTENT_FAILED'

export const FETCH_README_SUCCESS = 'FETCH_README_SUCCESS'
export const FETCH_README_FAILED = 'FETCH_README_FAILED'